### PR TITLE
Refactor: explicit db / model separation

### PR DESCRIPTION
**Pull request by rainbreak**
Should make things a bit easier to work with, and more obvious to a new developer.

Not defined an explicit frontend yet - the mananger is view + controller. Will do that separately.

### CODE REVIEW

**Comment by rainbreak** [comment]
All tests passing.

**Comment by nmushegian** [comment]
Is there any point to this if it's not intended to be upgradeable? These sorts of unadministered infrastructure contracts don't need this separation IMO, and it makes it harder to audit.

**Comment by nmushegian** [comment]
Ok nevermind I just realized what's going on. The names "Database" and "User" are confusing, "Database" implies it's a separate datastore contract and "User" is a utility mixin, not something that contains key functionality for the "used" contract

**Comment by rainbreak** [comment]
Yeah its all mixins. Only one distinct deployed contract. I actually had 'User' down as 'Frontend' initially.

I see this is a mid-term step. The manager was getting a bit god-like and I find it easier to work with smaller entities.

**Pull request merged**
